name: Cross build
on:
  push:
#    branches: [ "master" ]
  pull_request:
#    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: tecolicom/actions-use-apt-tools@v1.6
      with:
        tools: libgnutls28-dev
    - uses: carlosperate/arm-none-eabi-gcc-action@v1.10.1
      with:
        path-env-var: ARM_NONE_EABI_GCC_PATH
    - name: Set ARCH & CROSS_COMPILE environment variable
      run: |
        echo "ARCH=arm" >> $GITHUB_ENV
        echo "CROSS_COMPILE=$(echo "$ARM_NONE_EABI_GCC_PATH/arm-none-eabi-")" >> $GITHUB_ENV
    - name: Documentation - Crosscompiler switchs
      run: |
        "${{CROSS_COMPILE}}gcc" -print-multi-lib
        "${{CROSS_COMPILE}}gcc" --help
        "${{CROSS_COMPILE}}ld" --help
    - name: Build payloads
      run: |
        cd payloads
        make
    - name: Archive payloads artifacts
      uses: actions/upload-artifact@v4
      with:
          name: payloads
          path: payloads/**.bin
